drop
  table if exists authentication CASCADE;
drop
  table if exists channel_user_relations CASCADE;
drop
  table if exists channel_users CASCADE;
drop
  table if exists channel_view CASCADE;
drop
  table if exists channels CASCADE;
drop
  table if exists chat CASCADE;
drop
  table if exists chat_notice CASCADE;
drop
  table if exists content_detail CASCADE;
drop
  table if exists content_view CASCADE;
drop
  table if exists contents CASCADE;
drop
  table if exists interest CASCADE;
drop
  table if exists interest_relations CASCADE;
drop
  table if exists message_reaction CASCADE;
drop
  table if exists message_reaction_relations CASCADE;
drop
  table if exists notification CASCADE;
drop
  table if exists user_detail CASCADE;
drop
  table if exists users CASCADE;
create table authentication (
  id bigint generated by default as identity,
  role varchar(20) not null,
  user_id bigint,
  primary key (id)
);
create table channel_user_relations (
  id bigint generated by default as identity,
  channel_user_id bigint,
  joined_channel_id bigint,
  waiting_channel_id bigint,
  primary key (id)
);
create table channel_users (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  approve_request_at timestamp,
  exit_message varchar(255),
  refuse_message varchar(255),
  status varchar(255),
  user_id bigint,
  primary key (id)
);
create table channel_view (
  id bigint generated by default as identity,
  count bigint,
  channel_id bigint,
  primary key (id)
);
create table channels (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  content_id bigint,
  leader_user_id bigint,
  primary key (id)
);
create table chat (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  message varchar(255) not null,
  channel_id bigint,
  user_id bigint,
  primary key (id)
);
create table chat_notice (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  content varchar(255) not null,
  title varchar(255) not null,
  primary key (id)
);
create table content_detail (
  contents_id bigint not null,
  content_text clob not null,
  limit_people integer,
  location varchar(255) not null,
  name varchar(255) not null,
  online integer not null,
  purpose varchar(255) not null,
  recruit_method varchar(255) not null,
  recruit_period integer not null,
  primary key (contents_id)
);
create table content_view (
  id bigint generated by default as identity,
  count bigint,
  content_id bigint,
  primary key (id)
);
create table contents (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  content_type varchar(255) not null,
  primary key (id)
);
create table interest (
  id bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);
create table interest_relations (
  id bigint generated by default as identity,
  channel_id bigint,
  content_detail_id bigint,
  interest_id bigint,
  user_detail_id bigint,
  primary key (id)
);
create table message_reaction (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  reaction integer,
  user_id bigint,
  primary key (id)
);
create table message_reaction_relations (
  id bigint generated by default as identity,
  chat_id bigint,
  chat_notice_id bigint,
  reaction_id bigint,
  primary key (id)
);
create table notification (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  content varchar(255),
  title varchar(255),
  user_id bigint,
  primary key (id)
);
create table user_detail (
  user_id bigint not null,
  age integer not null,
  capability varchar(255),
  gender integer not null,
  introduce_text varchar(255),
  job varchar(50),
  profile_picture_uri varchar(255),
  username varchar(50) not null,
  primary key (user_id)
);
create table users (
  id bigint generated by default as identity,
  created_at timestamp,
  removed_at timestamp,
  updated_at timestamp,
  is_available boolean,
  password varchar(255),
  phone varchar(15),
  reason_for_withdrawal varchar(255),
  user_id bigint,
  primary key (id)
);
alter table
  contents
add
  constraint UK_9nmres2gx0eifs7ky57y8yn5i unique (content_type);
alter table
  interest
add
  constraint UK_n9khibjfvt2sanahgb13qslgd unique (name);
alter table
  authentication
add
  constraint FKkdfm8h65x6tk3a0xdhxy4blve foreign key (user_id) references users;
alter table
  channel_user_relations
add
  constraint FKcvq8el9nhdmk37oqho3thh8vl foreign key (channel_user_id) references channel_users;
alter table
  channel_user_relations
add
  constraint FK1n90f4mhw9liawow22j6g11q6 foreign key (joined_channel_id) references channels;
alter table
  channel_user_relations
add
  constraint FKjks1xfg8o3mlwpq0nakx1qw90 foreign key (waiting_channel_id) references channels;
alter table
  channel_users
add
  constraint FKd8th7utgty0qlood9tm8hdu foreign key (user_id) references users;
alter table
  channel_view
add
  constraint FK8mstc5arypj30qao75d862j1u foreign key (channel_id) references channels;
alter table
  channels
add
  constraint FKei9ht6c7ayf1fdpp2f3rvwep1 foreign key (content_id) references contents;
alter table
  channels
add
  constraint FKtqm3jdqqhs0ymp4w47c4bsxsb foreign key (leader_user_id) references users;
alter table
  chat
add
  constraint FKclpeyg3t0f7x4mftfriv56yjn foreign key (channel_id) references channels;
alter table
  chat
add
  constraint FK1x766u663l7m0mxuj0o72muu foreign key (user_id) references users;
alter table
  content_detail
add
  constraint FK5uhvb46t5wkxvi2b0tqooq0b9 foreign key (contents_id) references contents;
alter table
  content_view
add
  constraint FKm4g3rhrdo24wuefy4x4r88yb2 foreign key (content_id) references contents;
alter table
  interest_relations
add
  constraint FKo9b570lgvv22opvyd4rbriaxt foreign key (channel_id) references channels;
alter table
  interest_relations
add
  constraint FKa0yvq6l0hr3jxl59fub5hcoo0 foreign key (content_detail_id) references content_detail;
alter table
  interest_relations
add
  constraint FKggqkgp0xibjmno96mmq007jlb foreign key (interest_id) references interest;
alter table
  interest_relations
add
  constraint FKr5ttutm0om7yfiyifbg33jb35 foreign key (user_detail_id) references user_detail;
alter table
  message_reaction
add
  constraint FKe3ngmocd08j6nfeo1bxdtp8bh foreign key (user_id) references users;
alter table
  message_reaction_relations
add
  constraint FKso15ga4xbb6autfkb1hkocm5j foreign key (chat_id) references chat;
alter table
  message_reaction_relations
add
  constraint FK3pwkn70a1srb7l32agbn8v492 foreign key (chat_notice_id) references chat_notice;
alter table
  message_reaction_relations
add
  constraint FKiy642qutjo4ys49sektk2ed24 foreign key (reaction_id) references message_reaction;
alter table
  notification
add
  constraint FKnk4ftb5am9ubmkv1661h15ds9 foreign key (user_id) references users;
alter table
  user_detail
add
  constraint FKr6i0t96qgu9l8l5nn2vqo8rcl foreign key (user_id) references users;
alter table
  users
add
  constraint FKjogqshccrcue0m1009j4pquln foreign key (user_id) references content_view;
