create table device_token (
    id bigint generated by default as identity,
    created_at timestamp,
    removed_at timestamp,
    updated_at timestamp,
    arn varchar(200),
    token varchar(200) not null,
    user_id int8,
    primary key (id)
);

alter table device_token
   add constraint FKdklq4fbedbwx14v2varmsjeb5
   foreign key (user_id)
   references users;