drop table if exists notification CASCADE;

create table notification (
   id bigint generated by default as identity,
    created_at timestamp,
    removed_at timestamp,
    updated_at timestamp,
    message_type integer,
    read_at timestamp,
    channel_id bigint,
    receiver_user_id bigint not null,
    send_user_id bigint,
    primary key (id)
);

alter table notification
add constraint FKlnvre151ijirb49cyrdl5me7u
foreign key (channel_id)
references channels;

alter table notification
add constraint FK5ff4bedyvqdkynuqfl0873lwc
foreign key (receiver_user_id)
references users;

alter table notification
add constraint FKtqoeck59eap50tikmh0ss2am8
foreign key (send_user_id)
references users;